### ISSUE TITLE
Make: Model is not an option?

### ISSUE THREAD

**Issue by ghost** [dydx/Laravel-5-Artisan#4]
I've been trying to figure out how to run within Sublime Text 3:

Artisan: Make: Model and it's not displaying.

![screen shot 2015-09-28 at 4 55 28 pm](https://cloud.githubusercontent.com/assets/1234484/10149850/cec8013c-6601-11e5-871d-c15b0eb8c227.png)

I added https://github.com/laracasts/Laravel-5-Generators-Extended to my project and still nothing. Am I doing something wrong here?

Thanks in advance!

**Comment by dydx** [comment]
Interesting, I'll take a look at this. It's probably just a JSON error.

**Comment by dydx** [comment]
Yeah, it's listed here in the options: https://github.com/dydx/Laravel-5-Artisan/blob/master/Laravel%205%20Artisan.sublime-commands#L192,L199

Not sure what's going on / why it isn't listed.

Thanks for bringing this up!

**Comment by dydx** [comment]
Hmm. Having a hard time duplicating this on my machine (fresh install of ST3 w/ fresh install of the package).

![screenshot](http://i.imgur.com/JlCmErL.png)

Could you share some details about your setup? Sublime version and OS maybe?

**Comment by ghost** [comment]
@dydx I don't know what the difference was but I am now seeing this. Weird. Thanks for your time.
