### ISSUE TITLE
Make: Migration with --create="tableName" not possible

### ISSUE THREAD

**Issue by ghost** [dydx/Laravel-5-Artisan#5]
Just wanted to know if there is something I can do to get this option turned on, or is this something that is  not available?

**Comment by drickferreira** [comment]
I test with option --table=users and works fine.

Just enter at prompt [name of migration --table=users]

they create the structure to change the users table, not to create.

Maybe this works for you.

**Comment by ghost** [comment]
Okay, I'll try this and see if it works.

**Comment by dydx** [comment]
Did that approach work out for you?

**Comment by ghost** [comment]
@dydx it did, thank you
