### ISSUE TITLE
Latest version not available on Package Control

### ISSUE THREAD

**Issue by brianveltman** [dydx/Laravel-5-Artisan#6]
I'm using this package since today and noted the bug with make request, which actually creates a serviceprovider. Although this seems to be fixed 3 months ago, the version I installed through Package Control does not include this fix.

**Comment by dydx** [comment]
weird. I'll look into it! thanks for bringing this up.

**Comment by brianveltman** [comment]
You're welcome. Installed it manually, works great! :)
Although, any idea how to make it work with vagrant or homestead?

**Comment by dydx** [comment]
Yeah, there's a bit of an interop issue with running commands inside of virtual environments. I personally use Docker Compose locally, so there was some drive to get that done at least... but a few months ago we've all but switched to Rails for client work, and I've been using Vim more and more.

If you can think of a clever way to get virtual environment interop to work, feel free to PR it-- I'd love to see it working, I'm just not really sure where to start with it.

**Comment by brianveltman** [comment]
I'm not really familiar with Sublime yet. But I might give it a shot the next couple of weeks. Creating a build system to ssh into the virtual server seems quite easy. The real question is; what do we want? Specify a --vagrant flag to pass through the command to the vagrant instance? Or just set some defaults in the package config file? How to deal with multiple environments?
